// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart cortextos-daemon` switches instances without regenerating.
//
// Vision pre-call: when a Telegram image arrives at any agent, the daemon
// pre-calls Anthropic vision to convert it to a text description (raw image
// paths can't be injected into claude-code without triggering an image-poison
// crash). That pre-call needs ANTHROPIC_API_KEY at daemon-process scope.
// readClaudeOauthToken() pulls the Max-plan OAuth token from the macOS
// Keychain at PM2 start time, so token rotation is picked up on each restart.
// On non-macOS hosts or hosts without Claude Code installed, the helper
// returns '' and the daemon falls back to the suppressed-path stub message.
const os = require('os');
const { execFileSync } = require('child_process');
function readClaudeOauthToken() {
  if (process.platform !== 'darwin') return '';
  try {
    const out = execFileSync(
      'security',
      ['find-generic-password', '-s', 'Claude Code-credentials', '-a', os.userInfo().username, '-w'],
      { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'ignore'] }
    );
    return JSON.parse(out).claudeAiOauth.accessToken || '';
  } catch (_) {
    return '';
  }
}
module.exports = {
  apps: [
    {
      name: 'cortextos-daemon',
      script: "/Users/swilson/projects/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/Users/swilson/projects/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/Users/swilson/.cortextos/default",
        CTX_FRAMEWORK_ROOT: "/Users/swilson/projects/cortextos",
        CTX_PROJECT_ROOT: "/Users/swilson/projects/cortextos",
        CTX_ORG: process.env.CTX_ORG || "bonayrindustries",
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY || readClaudeOauthToken(),
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'cortextos-dashboard',
      script: "npm",
      args: "run dev",
      cwd: "/Users/swilson/projects/cortextos/dashboard",
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the dashboard process.
      windowsHide: true,
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
